SC_home_assignment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('einstein_app.urls')),
]

einstein_app/urls.py
from django.urls import path
from . import views

app_name = 'einstein_app'
urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('hebrew/', views.hebrewVer, name='hebrew'),

]

einstein_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Course(models.Model):
    title = models.CharField(max_length=80)
    description = models.CharField(max_length=320, null=True)
    category = models.ForeignKey('Category', blank=True, null=True, related_name='course_category', on_delete=models.SET_NULL)
    by_user = models.ForeignKey(User, blank=True, null=True, related_name='by_user', on_delete=models.SET_NULL)
    enrolled_users = models.ManyToManyField(User, blank=True, related_name='enrolled_users')
    creation_date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=80)
    
    def __str__(self):
        return self.name


class Contact(models.Model):
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField(max_length=11, null=True, blank=True)
    topic = models.CharField(max_length=80)
    message = models.TextField(max_length=320, null=True, blank=True)
    time_sent = models.DateTimeField(auto_now_add=True)
    answer = models.TextField(max_length=320, null=True, blank=True)

    def __str__(self):
        return self.first_name + ' ' + self.last_name + ': '
        + self.topic + ' ' + self.time_sent.strftime("%m/%d/%Y, %H:%M:%S")

einstein_app/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .models import *

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'einstein_app/home.html'
    context_object_name = 'categories'

    def get_queryset(self):
        categories_list = Category.objects.all()
        courses_list = Course.objects.all()

        category_dict = {}
        for current_category in categories_list:
            current_courses =  [course for course in courses_list if course.category == current_category]
            category_dict[current_category.name] = current_courses[:6]
        
        return category_dict

def hebrewVer(request):
    return render(request, 'einstein_app/hebrew.html')

einstein_app/templates/einstein_app/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Einstein - SC home assignment</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://kit.fontawesome.com/3966e5acfc.js" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href={% static 'css/style.css' %}>
    </head>
    <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
        <a class="navbar-brand" href="#"><img id="main_logo" src={% static "images/einstein_logo.jpg" %}></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto nav nav-tabs pull-right" style="float: right;">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" href=""><strong>Hello, {{ user.username }}</strong></a>
              </li>
            {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'einstein_app:home' %}">Home</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="">About Us</a>
                </li>
              <li class="nav-item">
                <a class="nav-link" href="">Contact Us</a>
              </li>
          
              {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="">Logout</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="">Login</a>
                </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'einstein_app:hebrew' %}"><i class="fas fa-globe"> עב</i>
                </a>
              </li>
          </ul>
        </div>
      </nav>

      {% block content %}
      {% endblock %}
        
      <footer>
        <hr>
        --- Einstein home assignment by Liran Sharabi --- 
      </footer>
    </body>
</html>

einstein_app/templates/einstein_app/hebrew.html
{% extends 'einstein_app/base.html' %}

{% block content %}
<h2>גרסא עברית - דף בבנייה</h2>
{% endblock %}

einstein_app/templates/einstein_app/home.html
{% extends 'einstein_app/base.html' %}

{% block content %}
{% load static %}
    <div class="hero">
        <img src={% static "images/love_to_learn.jpg" %} alt="hero pic">
    </div>
    <h2>Courses by Category</h2>
    <br>
        {% if categories %}
            {% for category, current_courses in categories.items %}
                <div>
                    <br>
                    <br>
                    <h3 class="category-title"><i class="fas fa-layer-group"></i>  {{ category }}</h3>
                    <hr>
                    <br>
                    <div class="grid-container-max6">
                        {% if current_courses %}
                            {% for course in current_courses %}
                                <div class="grid-container-card">
                                    <div class="course-picture">
                                        <img src="https://images.unsplash.com/photo-1517148815978-75f6acaaf32c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="course picture">
                                    </div>
                                    <div class="course-text">
                                        <h3>{{ course.title }}</h3>
                                        <p>by {{ course.by_user }}</p>
                                        <p><i class="fas fa-plus-circle"></i> Read More</p>
                                    </div>
                                </div>                  
                            {% endfor %}
                        {% else %}
                            <p>No Available Courses.</p>
                        {% endif %}  
                    </div> 
                </div>                  
            {% endfor %}    
        {% else %}
            <p>No Available Categories.</p>
        {% endif %}      
{% endblock %}